"use client";

import { useTool } from "@/hooks/useTool";
import Button from "@/components/ui/Button";
import TextArea from "@/components/ui/TextArea";
import ToolContainer from "@/components/ui/ToolContainer";

export default function JsonToGoStructTool() {
  const { input, setInput, output, setOutput, clearAll } = useTool();

  const convert = () => {
    try {
      const json = JSON.parse(input);
      const toGo = (obj: any, name: string = "AutoGenerated"): string => {
        let go = `type ${name} struct {\n`;
        for (const key in obj) {
          const val = obj[key];
          const camelKey = key.replace(/([-_][a-z])/gi, ($1) => $1.toUpperCase().replace('-', '').replace('_', ''));
          const pascalKey = camelKey.charAt(0).toUpperCase() + camelKey.slice(1);
          
          let type = "interface{}";
          if (typeof val === "string") type = "string";
          else if (typeof val === "number") type = Number.isInteger(val) ? "int" : "float64";
          else if (typeof val === "boolean") type = "bool";
          else if (Array.isArray(val)) type = "[]interface{}";
          else if (typeof val === "object" && val !== null) type = "struct { ... }";

          go += `\t${pascalKey} ${type} \`json:"${key}"\`\n`;
        }
        go += "}";
        return go;
      };
      setOutput(toGo(json));
    } catch (e) {
      setOutput("Invalid JSON input.");
    }
  };

  return (
    <ToolContainer title="JSON to Go Struct" description="Convert JSON objects to Go (Golang) struct definitions.">
      <TextArea
        label="JSON Input"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        placeholder='{ "id": 1, "name": "John" }'
        rows={10}
      />
      <div className="mt-4 flex gap-2">
        <Button onClick={convert}>Convert to Go</Button>
        <Button variant="ghost" onClick={clearAll}>Clear</Button>
      </div>
      {output && (
        <TextArea
          label="Go Struct Output"
          value={output}
          readOnly
          className="mt-6"
          copyable
          rows={10}
        />
      )}
    </ToolContainer>
  );
}
