"use client";

import { useState, useMemo } from "react";
import Button from "@/components/ui/Button";
import TextArea from "@/components/ui/TextArea";
import ToolContainer from "@/components/ui/ToolContainer";

export default function RobotsTxtGeneratorTool() {
  const [defaultAccess, setDefaultAccess] = useState<"allow" | "disallow">("allow");
  const [disallowedPaths, setDisallowedPaths] = useState("/admin/\n/private/\n/api/");
  const [allowedPaths, setAllowedPaths] = useState("/public/\n/images/");
  const [sitemapUrl, setSitemapUrl] = useState("https://example.com/sitemap.xml");
  const [crawlDelay, setCrawlDelay] = useState("5");
  const [blockAiBots, setBlockAiBots] = useState(false);
  const [isCopied, setIsCopied] = useState(false);

  const generatedRobots = useMemo(() => {
    let txt = `# robots.txt generated by ToolSnippet (https://www.toolsnippet.com/tools/robots-txt-generator)\n\n`;

    // Standard User-Agent
    txt += `User-agent: *\n`;
    if (defaultAccess === "disallow") {
      txt += `Disallow: /\n`;
    }

    if (allowedPaths.trim()) {
      allowedPaths
        .split("\n")
        .map((p) => p.trim())
        .filter(Boolean)
        .forEach((path) => {
          txt += `Allow: ${path.startsWith("/") ? path : `/${path}`}\n`;
        });
    }

    if (disallowedPaths.trim()) {
      disallowedPaths
        .split("\n")
        .map((p) => p.trim())
        .filter(Boolean)
        .forEach((path) => {
          txt += `Disallow: ${path.startsWith("/") ? path : `/${path}`}\n`;
        });
    }

    if (crawlDelay.trim() && parseInt(crawlDelay) > 0) {
      txt += `Crawl-delay: ${crawlDelay.trim()}\n`;
    }

    if (blockAiBots) {
      txt += `\n# Disallow common AI scraping bots\n`;
      const aiBots = ["GPTBot", "ChatGPT-User", "CCBot", "anthropic-ai", "ClaudeBot", "Google-Extended", "Bytespider"];
      aiBots.forEach((bot) => {
        txt += `User-agent: ${bot}\nDisallow: /\n\n`;
      });
    }

    if (sitemapUrl.trim()) {
      txt += `\nSitemap: ${sitemapUrl.trim()}\n`;
    }

    return txt.trim();
  }, [defaultAccess, disallowedPaths, allowedPaths, sitemapUrl, crawlDelay, blockAiBots]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedRobots);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  return (
    <ToolContainer
      title="Robots.txt Generator"
      description="Create search engine crawler rules, disallow private directories, and define sitemap locations."
      maxWidth="5xl"
    >
      <div className="grid gap-6">
        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <label className="block text-sm font-medium mb-1">Default Crawler Policy</label>
            <select
              value={defaultAccess}
              onChange={(e) => setDefaultAccess(e.target.value as "allow" | "disallow")}
              className="w-full rounded-lg border border-black/15 bg-transparent p-3 text-sm outline-none focus:ring-2 focus:ring-primary dark:border-white/20"
            >
              <option value="allow">Allow All Crawlers by Default</option>
              <option value="disallow">Disallow All Crawlers by Default</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium mb-1">Sitemap URL</label>
            <input
              type="text"
              value={sitemapUrl}
              onChange={(e) => setSitemapUrl(e.target.value)}
              placeholder="https://example.com/sitemap.xml"
              className="w-full rounded-lg border border-black/15 bg-transparent p-3 text-sm outline-none focus:ring-2 focus:ring-primary dark:border-white/20"
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-1">Disallowed Paths (one per line)</label>
            <textarea
              value={disallowedPaths}
              onChange={(e) => setDisallowedPaths(e.target.value)}
              rows={4}
              placeholder="/admin/\n/checkout/\n/tmp/"
              className="w-full font-mono text-sm rounded-lg border border-black/15 bg-transparent p-3 outline-none focus:ring-2 focus:ring-primary dark:border-white/20"
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-1">Allowed Paths (one per line)</label>
            <textarea
              value={allowedPaths}
              onChange={(e) => setAllowedPaths(e.target.value)}
              rows={4}
              placeholder="/public/\n/blog/"
              className="w-full font-mono text-sm rounded-lg border border-black/15 bg-transparent p-3 outline-none focus:ring-2 focus:ring-primary dark:border-white/20"
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-1">Crawl Delay (seconds, optional)</label>
            <input
              type="number"
              min="0"
              max="60"
              value={crawlDelay}
              onChange={(e) => setCrawlDelay(e.target.value)}
              placeholder="e.g. 5"
              className="w-full rounded-lg border border-black/15 bg-transparent p-3 text-sm outline-none focus:ring-2 focus:ring-primary dark:border-white/20"
            />
          </div>

          <div className="flex items-center pt-6">
            <label className="flex items-center gap-2 cursor-pointer text-sm font-medium">
              <input
                type="checkbox"
                checked={blockAiBots}
                onChange={(e) => setBlockAiBots(e.target.checked)}
                className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
              />
              <span>Block AI Web Scraping Crawlers (GPTBot, CCBot, etc.)</span>
            </label>
          </div>
        </div>

        <div className="flex gap-2">
          <Button onClick={handleCopy}>
            {isCopied ? "Copied Robots.txt!" : "Copy Robots.txt"}
          </Button>
        </div>

        <TextArea
          label="Generated robots.txt"
          readOnly
          copyable
          value={generatedRobots}
          rows={12}
        />
      </div>
    </ToolContainer>
  );
}
